"""empty message

Revision ID: ad65e34c3dc6
Revises: c53b1999693d
Create Date: 2023-01-16 23:13:25.988656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad65e34c3dc6'
down_revision = 'c53b1999693d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prevision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rut', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('prevision_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['rut'])
        batch_op.create_foreign_key(None, 'prevision', ['prevision_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('prevision_id')
        batch_op.drop_column('password')
        batch_op.drop_column('rut')

    op.drop_table('prevision')
    # ### end Alembic commands ###
